Remove unused Q_Q macros which caused fatal warnings
error: unused variable ‘q’ [-Werror=unused-variable]

Amends 59ae054ded4d74db53281d8087576cd05b979cd9

Pick-to: 6.7
Change-Id: I8d506ba04723fa9327bbc80e2597d2176e500c2d
Reviewed-by: David Edmundson <davidedmundson@kde.org>