brcm-egl: needs wayland-scanner-client-wayland-protocol-include
Fixes:

  wayland-brcm-client-protocol.h: In function ‘wl_buffer* qt_brcm_create_buffer(qt_brcm*, int32_t, int32_t, wl_array*)’:
  wayland-brcm-client-protocol.h:115:29: error: ‘wl_buffer_interface’ was not declared in this scope; did you mean ‘qt_brcm_interface’?
    115 |     QT_BRCM_CREATE_BUFFER, &wl_buffer_interface, NULL, width, height, data);
        |                             ^~~~~~~~~~~~~~~~~~~
        |                             qt_brcm_interface

Task-number: QTBUG-83305
Change-Id: I16789c5df73e8f17ad98d91cadf2478d39dcba9e
Reviewed-by: Eskil Abrahamsen Blomfeldt <eskil.abrahamsen-blomfeldt@qt.io>
(cherry picked from commit c65e013527e144028d2d7c03fe1b503fb21aa89d)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>