Fix build: xcomposite-xxx depend on QtPlatformSupport
qwaylandxcompositeeglcontext.h:47:10: fatal error:  'QtPlatformSupport/private/qeglplatformcontext_p.h' file not found

Change-Id: I149e0540c00745fe8119fffd146455b90946cacf
Reviewed-by: Jan Arne Petersen <jan.petersen@kdab.com>
Reviewed-by: Johan Helsing <johan.helsing@qt.io>
Reviewed-by: Giulio Camuffo <giulio.camuffo@kdab.com>