Fix build: update to QPA API
wltouch.cpp:146:63: error: conversion from ‘QVector<QPointF>’ to non-scalar type ‘QList<QPointF>’ requested

Change-Id: Ibcf6c547fa1eeee2ccd568f60c10146ab104ce81
Reviewed-by: Jørgen Lind <jorgen.lind@nokia.com>