Fix failure to build from sources: missing #include
qwaylandinputdeviceintegration_p.h:64:85: error: ‘uint32_t’ has not been declared

Change-Id: Ic747cc2ab45e4dc6bb70ffff143843d1ed4a341b
Reviewed-by: Lars Knoll <lars.knoll@theqtcompany.com>