Remove unused Q_Q macros which caused fatal warnings
error: unused variable ‘q’ [-Werror=unused-variable]

Amends 59ae054ded4d74db53281d8087576cd05b979cd9

Change-Id: I8d506ba04723fa9327bbc80e2597d2176e500c2d
Reviewed-by: David Edmundson <davidedmundson@kde.org>
(cherry picked from commit 92ba57d7ceca3d9d072ee121ab44eff17637cbec)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>