Fix build: some shells need to link to libxkbcommon
They use QtWaylandClient's private headers.

In file included from qwaylandinputdevice_p.h:1,
                 from qwaylandxdgshellv6.cpp:45:
qwaylandinputdevice_p.h:69:10: fatal error: xkbcommon/xkbcommon.h: No such file or directory

Change-Id: I6efb28c3145047559ec0fffd1538a642167da67f
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@qt.io>
Reviewed-by: Johan Helsing <johan.helsing@qt.io>