Fix build on CentOS 7
Have the following errors while attempting to build qtwayland v6.5.0-beta3:
    /usr/src/Libraries/qt_6.5.0/qtwayland/src/client/qwaylandshmbackingstore.cpp:48:19: error: 'F_ADD_SEALS' was not declared in this scope
       48 |         fcntl(fd, F_ADD_SEALS, F_SEAL_SHRINK | F_SEAL_SEAL);
          |                   ^~~~~~~~~~~
    /usr/src/Libraries/qt_6.5.0/qtwayland/src/client/qwaylandshmbackingstore.cpp:48:32: error: 'F_SEAL_SHRINK' was not declared in this scope
       48 |         fcntl(fd, F_ADD_SEALS, F_SEAL_SHRINK | F_SEAL_SEAL);
          |                                ^~~~~~~~~~~~~
    /usr/src/Libraries/qt_6.5.0/qtwayland/src/client/qwaylandshmbackingstore.cpp:48:48: error: 'F_SEAL_SEAL' was not declared in this scope
       48 |         fcntl(fd, F_ADD_SEALS, F_SEAL_SHRINK | F_SEAL_SEAL);
          |                                                ^~~~~~~~~~~

Change-Id: I4b9b3a13ac47483594f454ba36dc5d720cb592a5
Reviewed-by: Vlad Zahorodnii <vlad.zahorodnii@kde.org>
Reviewed-by: David Edmundson <davidedmundson@kde.org>
(cherry picked from commit 12da86346954f7290e3e1fb00f5c5f2307d2fd58)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>